# Configuration/Services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Codappix\ResponsiveImages\:
        resource: '../Classes/*'

    dbconnection.tt_content:
        class: 'TYPO3\CMS\Core\Database\Connection'
        factory:
            - '@TYPO3\CMS\Core\Database\ConnectionPool'
            - 'getConnectionForTable'
        arguments:
            - 'tt_content'

    extbaseSettings.ResponsiveImages:
        class: 'array'
        factory:
            - '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
            - 'getConfiguration'
        arguments:
            $configurationType: 'Settings'
            $extensionName: 'ResponsiveImages'
            $pluginName: ''

    Codappix\ResponsiveImages\DataProcessing\ResponsiveImagesProcessor:
        public: true
        arguments:
            $configurationManager: '@Codappix\ResponsiveImages\Configuration\ConfigurationManager'
            $containerRepository: '@Codappix\ResponsiveImages\Domain\Repository\ContainerRepository'

    Codappix\ResponsiveImages\Configuration\ConfigurationManager:
        public: true
        arguments:
            $settings: '@extbaseSettings.ResponsiveImages'

    Codappix\ResponsiveImages\Domain\Repository\ContainerRepository:
        public: true
        arguments:
            - '@dbconnection.tt_content'
